import path from 'path';
import { AccountProfileConfig, AppConfig } from './types';
import {
    parseBoolEnv,
    parseCsvEnv,
    parseEventSyncSinkEnv,
    parseFloatEnv,
    parseIntEnv,
    parseProxyType,
    parseStringEnv,
    resolvePathFromEnv,
} from './env';

export function buildRuntimeDomainConfig(accountProfiles: AccountProfileConfig[]): Partial<AppConfig> {
    return {
        timezone: process.env.TIMEZONE ?? 'Europe/Rome',
        headless: parseBoolEnv('HEADLESS', false),
        dashboardAuthEnabled: parseBoolEnv('DASHBOARD_AUTH_ENABLED', true),
        dashboardApiKey: parseStringEnv('DASHBOARD_API_KEY'),
        dashboardBasicUser: parseStringEnv('DASHBOARD_BASIC_USER'),
        dashboardBasicPassword: parseStringEnv('DASHBOARD_BASIC_PASSWORD'),
        dashboardTrustedIps: parseCsvEnv('DASHBOARD_TRUSTED_IPS'),
        workingHoursStart: parseIntEnv('HOUR_START', 9),
        workingHoursEnd: parseIntEnv('HOUR_END', 18),
        jobStuckMinutes: Math.max(1, parseIntEnv('JOB_STUCK_MINUTES', 30)),
        retryMaxAttempts: Math.max(1, parseIntEnv('RETRY_MAX_ATTEMPTS', 3)),
        retryBaseMs: Math.max(100, parseIntEnv('RETRY_BASE_MS', 1200)),
        integrationRetryMaxAttempts: Math.max(1, parseIntEnv('INTEGRATION_RETRY_MAX_ATTEMPTS', parseIntEnv('RETRY_MAX_ATTEMPTS', 3))),
        integrationRetryMaxDelayMs: Math.max(500, parseIntEnv('INTEGRATION_RETRY_MAX_DELAY_MS', 30_000)),
        integrationRequestTimeoutMs: Math.max(250, parseIntEnv('INTEGRATION_REQUEST_TIMEOUT_MS', 10_000)),
        integrationCircuitBreakerEnabled: parseBoolEnv('INTEGRATION_CIRCUIT_BREAKER_ENABLED', true),
        integrationCircuitFailureThreshold: Math.max(1, parseIntEnv('INTEGRATION_CIRCUIT_FAILURE_THRESHOLD', 5)),
        integrationCircuitOpenMs: Math.max(1000, parseIntEnv('INTEGRATION_CIRCUIT_OPEN_MS', 60_000)),
        workflowLoopIntervalMs: Math.max(10_000, parseIntEnv('WORKFLOW_LOOP_INTERVAL_MS', 900000)),
        companyEnrichmentEnabled: parseBoolEnv('COMPANY_ENRICHMENT_ENABLED', true),
        companyEnrichmentBatch: Math.max(1, parseIntEnv('COMPANY_ENRICHMENT_BATCH', 5)),
        companyEnrichmentMaxProfilesPerCompany: Math.max(1, parseIntEnv('COMPANY_ENRICHMENT_MAX_PROFILES_PER_COMPANY', 3)),
        maxConsecutiveJobFailures: Math.max(1, parseIntEnv('MAX_CONSECUTIVE_JOB_FAILURES', 4)),
        maxSelectorFailuresPerDay: Math.max(1, parseIntEnv('MAX_SELECTOR_FAILURES_PER_DAY', 8)),
        maxRunErrorsPerDay: Math.max(1, parseIntEnv('MAX_RUN_ERRORS_PER_DAY', 20)),
        accountMaxJobsPerRun: Math.max(1, parseIntEnv('ACCOUNT_MAX_JOBS_PER_RUN', 120)),
        accountLegacyDefaultQueueFallback: parseBoolEnv('ACCOUNT_LEGACY_DEFAULT_QUEUE_FALLBACK', false),
        accountHealthWarnFailureRate: Math.min(1, Math.max(0, parseFloatEnv('ACCOUNT_HEALTH_WARN_FAILURE_RATE', 0.2))),
        accountHealthCriticalFailureRate: Math.min(1, Math.max(0, parseFloatEnv('ACCOUNT_HEALTH_CRITICAL_FAILURE_RATE', 0.35))),
        accountHealthAlertMinProcessed: Math.max(1, parseIntEnv('ACCOUNT_HEALTH_ALERT_MIN_PROCESSED', 5)),
        autoPauseMinutesOnFailureBurst: Math.max(1, parseIntEnv('AUTO_PAUSE_MINUTES_ON_FAILURE_BURST', 180)),
        challengePauseMinutes: Math.max(5, parseIntEnv('CHALLENGE_PAUSE_MINUTES', 180)),
        retentionDays: Math.max(7, parseIntEnv('RETENTION_DAYS', 90)),
        profileContextExtractionEnabled: parseBoolEnv('PROFILE_CONTEXT_EXTRACTION_ENABLED', false),
        sessionDir: resolvePathFromEnv('SESSION_DIR', path.join('data', 'session')),
        multiAccountEnabled: parseBoolEnv('MULTI_ACCOUNT_ENABLED', accountProfiles.length > 1),
        accountProfiles,
        dbPath: resolvePathFromEnv('DB_PATH', path.join('data', 'linkedin_bot.sqlite')),
        databaseUrl: parseStringEnv('DATABASE_URL'),
        allowSqliteInProduction: parseBoolEnv('ALLOW_SQLITE_IN_PRODUCTION', false),
        eventSyncSink: parseEventSyncSinkEnv('EVENT_SYNC_SINK', 'SUPABASE'),
    };
}

export function buildLimitsAndRiskDomainConfig(): Partial<AppConfig> {
    return {
        softInviteCap: Math.max(1, parseIntEnv('SOFT_INVITE_CAP', 25)),
        hardInviteCap: Math.max(1, parseIntEnv('HARD_INVITE_CAP', 35)),
        weeklyInviteLimit: Math.max(1, parseIntEnv('WEEKLY_INVITE_LIMIT', 120)),
        softMsgCap: Math.max(1, parseIntEnv('SOFT_MSG_CAP', 40)),
        hardMsgCap: Math.max(1, parseIntEnv('HARD_MSG_CAP', 60)),
        complianceEnforced: parseBoolEnv('COMPLIANCE_ENFORCED', true),
        complianceMaxHardInviteCap: Math.max(1, parseIntEnv('COMPLIANCE_MAX_HARD_INVITE_CAP', 20)),
        complianceMaxWeeklyInviteLimit: Math.max(1, parseIntEnv('COMPLIANCE_MAX_WEEKLY_INVITE_LIMIT', 100)),
        complianceMaxHardMsgCap: Math.max(1, parseIntEnv('COMPLIANCE_MAX_HARD_MSG_CAP', 40)),
        messageScheduleMinDelayHours: Math.max(0, parseIntEnv('MESSAGE_SCHEDULE_MIN_DELAY_HOURS', 0)),
        messageScheduleMaxDelayHours: Math.max(0, parseIntEnv('MESSAGE_SCHEDULE_MAX_DELAY_HOURS', 0)),
        riskWarnThreshold: parseIntEnv('RISK_WARN_THRESHOLD', 60),
        lowActivityEnabled: parseBoolEnv('LOW_ACTIVITY_ENABLED', true),
        lowActivityRiskThreshold: Math.max(0, parseIntEnv('LOW_ACTIVITY_RISK_THRESHOLD', 70)),
        lowActivityPendingThreshold: Math.min(1, Math.max(0, parseFloatEnv('LOW_ACTIVITY_PENDING_THRESHOLD', 0.6))),
        lowActivityBudgetFactor: Math.min(1, Math.max(0.01, parseFloatEnv('LOW_ACTIVITY_BUDGET_FACTOR', 0.2))),
        lowActivityMinBudget: Math.max(1, parseIntEnv('LOW_ACTIVITY_MIN_BUDGET', 2)),
        riskStopThreshold: parseIntEnv('RISK_STOP_THRESHOLD', 80),
        pendingRatioWarn: parseFloatEnv('PENDING_RATIO_WARN', 0.65),
        pendingRatioStop: parseFloatEnv('PENDING_RATIO_STOP', 0.8),
        adaptiveCapsEnabled: parseBoolEnv('ADAPTIVE_CAPS_ENABLED', true),
        adaptiveCapsPendingWarn: Math.min(1, Math.max(0, parseFloatEnv('ADAPTIVE_CAPS_PENDING_WARN', 0.55))),
        adaptiveCapsPendingStop: Math.min(1, Math.max(0, parseFloatEnv('ADAPTIVE_CAPS_PENDING_STOP', 0.72))),
        adaptiveCapsBlockedWarn: Math.min(1, Math.max(0, parseFloatEnv('ADAPTIVE_CAPS_BLOCKED_WARN', 0.25))),
        adaptiveCapsMinFactor: Math.min(1, Math.max(0.05, parseFloatEnv('ADAPTIVE_CAPS_MIN_FACTOR', 0.25))),
        adaptiveCapsWarnFactor: Math.min(1, Math.max(0.05, parseFloatEnv('ADAPTIVE_CAPS_WARN_FACTOR', 0.85))),
        cooldownEnabled: parseBoolEnv('COOLDOWN_ENABLED', true),
        cooldownWarnScore: Math.max(0, parseIntEnv('COOLDOWN_WARN_SCORE', 68)),
        cooldownHighScore: Math.max(0, parseIntEnv('COOLDOWN_HIGH_SCORE', 75)),
        cooldownPendingThreshold: Math.min(1, Math.max(0, parseFloatEnv('COOLDOWN_PENDING_THRESHOLD', 0.65))),
        cooldownPendingHighThreshold: Math.min(1, Math.max(0, parseFloatEnv('COOLDOWN_PENDING_HIGH_THRESHOLD', 0.75))),
        cooldownWarnMinutes: Math.max(10, parseIntEnv('COOLDOWN_WARN_MINUTES', 2880)),
        cooldownHighMinutes: Math.max(10, parseIntEnv('COOLDOWN_HIGH_MINUTES', 4320)),
        noBurstEnabled: parseBoolEnv('NO_BURST_ENABLED', true),
        noBurstMinDelaySec: Math.max(0, parseIntEnv('NO_BURST_MIN_DELAY_SEC', 8)),
        noBurstMaxDelaySec: Math.max(0, parseIntEnv('NO_BURST_MAX_DELAY_SEC', 25)),
        noBurstLongBreakEvery: Math.max(0, parseIntEnv('NO_BURST_LONG_BREAK_EVERY', 7)),
        noBurstLongBreakMinSec: Math.max(0, parseIntEnv('NO_BURST_LONG_BREAK_MIN_SEC', 120)),
        noBurstLongBreakMaxSec: Math.max(0, parseIntEnv('NO_BURST_LONG_BREAK_MAX_SEC', 360)),
        autoSiteCheckEnabled: parseBoolEnv('AUTO_SITE_CHECK_ENABLED', true),
        autoSiteCheckLimit: Math.max(1, parseIntEnv('AUTO_SITE_CHECK_LIMIT', 20)),
        autoSiteCheckFix: parseBoolEnv('AUTO_SITE_CHECK_FIX', true),
        autoSiteCheckIntervalHours: Math.max(1, parseIntEnv('AUTO_SITE_CHECK_INTERVAL_HOURS', 24)),
        siteCheckStaleDays: Math.max(0, parseIntEnv('SITE_CHECK_STALE_DAYS', 2)),
        postRunStateSyncEnabled: parseBoolEnv('POST_RUN_STATE_SYNC_ENABLED', true),
        postRunStateSyncLimit: Math.max(1, parseIntEnv('POST_RUN_STATE_SYNC_LIMIT', 8)),
        postRunStateSyncFix: parseBoolEnv('POST_RUN_STATE_SYNC_FIX', true),
        selectorCanaryEnabled: parseBoolEnv('SELECTOR_CANARY_ENABLED', true),
        outboxAlertBacklog: Math.max(1, parseIntEnv('OUTBOX_ALERT_BACKLOG', 1000)),
        riskPredictiveAlertsEnabled: parseBoolEnv('RISK_PREDICTIVE_ALERTS_ENABLED', true),
        riskPredictiveLookbackDays: Math.max(3, parseIntEnv('RISK_PREDICTIVE_LOOKBACK_DAYS', 7)),
        riskPredictiveSigma: Math.max(0.5, parseFloatEnv('RISK_PREDICTIVE_SIGMA', 2)),
    };
}

export function buildSyncDomainConfig(): Partial<AppConfig> {
    return {
        supabaseSyncEnabled: parseBoolEnv('SUPABASE_SYNC_ENABLED', true),
        supabaseUrl: parseStringEnv('SUPABASE_URL'),
        supabaseServiceRoleKey: parseStringEnv('SUPABASE_SERVICE_ROLE_KEY'),
        supabaseSyncBatchSize: Math.max(1, parseIntEnv('SUPABASE_SYNC_BATCH_SIZE', 100)),
        supabaseSyncIntervalMs: Math.max(1000, parseIntEnv('SUPABASE_SYNC_INTERVAL_MS', 15000)),
        supabaseSyncMaxRetries: Math.max(1, parseIntEnv('SUPABASE_SYNC_MAX_RETRIES', 8)),
        supabaseControlPlaneEnabled: parseBoolEnv('SUPABASE_CONTROL_PLANE_ENABLED', false),
        supabaseControlPlaneSyncIntervalMs: Math.max(1000, parseIntEnv('SUPABASE_CONTROL_PLANE_SYNC_INTERVAL_MS', 300000)),
        supabaseControlPlaneMaxCampaigns: Math.max(1, parseIntEnv('SUPABASE_CONTROL_PLANE_MAX_CAMPAIGNS', 500)),
        webhookSyncEnabled: parseBoolEnv('WEBHOOK_SYNC_ENABLED', false),
        webhookSyncUrl: parseStringEnv('WEBHOOK_SYNC_URL'),
        webhookSyncSecret: parseStringEnv('WEBHOOK_SYNC_SECRET'),
        webhookSyncBatchSize: Math.max(1, parseIntEnv('WEBHOOK_SYNC_BATCH_SIZE', 100)),
        webhookSyncTimeoutMs: Math.max(1000, parseIntEnv('WEBHOOK_SYNC_TIMEOUT_MS', 10000)),
        webhookSyncMaxRetries: Math.max(1, parseIntEnv('WEBHOOK_SYNC_MAX_RETRIES', 8)),
    };
}

export function buildAiDomainConfig(): Partial<AppConfig> {
    return {
        openaiApiKey: parseStringEnv('OPENAI_API_KEY'),
        openaiBaseUrl: parseStringEnv('OPENAI_BASE_URL', 'http://127.0.0.1:11434/v1'),
        aiModel: parseStringEnv('AI_MODEL', 'llama3.1:8b'),
        aiAllowRemoteEndpoint: parseBoolEnv('AI_ALLOW_REMOTE_ENDPOINT', false),
        aiRequestTimeoutMs: Math.max(1000, parseIntEnv('AI_REQUEST_TIMEOUT_MS', 12000)),
        aiPersonalizationEnabled: parseBoolEnv('AI_PERSONALIZATION_ENABLED', false),
        aiSentimentEnabled: parseBoolEnv('AI_SENTIMENT_ENABLED', false),
        aiMessageMaxChars: Math.max(120, parseIntEnv('AI_MESSAGE_MAX_CHARS', 450)),
        aiQualityMinSampleSize: Math.max(5, parseIntEnv('AI_QUALITY_MIN_SAMPLE_SIZE', 30)),
        aiQualitySignificanceAlpha: Math.min(0.25, Math.max(0.001, parseFloatEnv('AI_QUALITY_SIGNIFICANCE_ALPHA', 0.05))),
        aiValidationAutoSeedEnabled: parseBoolEnv('AI_VALIDATION_AUTO_SEED_ENABLED', true),
        aiGuardianEnabled: parseBoolEnv('AI_GUARDIAN_ENABLED', false),
        aiGuardianMinIntervalMinutes: Math.max(1, parseIntEnv('AI_GUARDIAN_MIN_INTERVAL_MINUTES', 60)),
        aiGuardianPauseMinutes: Math.max(10, parseIntEnv('AI_GUARDIAN_PAUSE_MINUTES', 180)),
        aiGreenModel: parseStringEnv('AI_GREEN_MODEL', 'llama3.1:8b'),
    };
}

export function buildCommsAndBusinessDomainConfig(): Partial<AppConfig> {
    return {
        telegramBotToken: parseStringEnv('TELEGRAM_BOT_TOKEN'),
        telegramChatId: parseStringEnv('TELEGRAM_CHAT_ID'),
        discordWebhookUrl: parseStringEnv('DISCORD_WEBHOOK_URL'),
        slackWebhookUrl: parseStringEnv('SLACK_WEBHOOK_URL'),
        backupRetentionDays: Math.max(1, parseIntEnv('BACKUP_RETENTION_DAYS', 7)),
        securitySecretMaxAgeDays: Math.max(1, parseIntEnv('SECURITY_SECRET_MAX_AGE_DAYS', 90)),
        securitySecretWarnDays: Math.max(1, parseIntEnv('SECURITY_SECRET_WARN_DAYS', 14)),
        processMaxUptimeHours: Math.max(1, parseIntEnv('PROCESS_MAX_UPTIME_HOURS', 24)),
        hubspotApiKey: parseStringEnv('HUBSPOT_API_KEY'),
        salesforceInstanceUrl: parseStringEnv('SALESFORCE_INSTANCE_URL'),
        salesforceClientId: parseStringEnv('SALESFORCE_CLIENT_ID'),
        salesforceClientSecret: parseStringEnv('SALESFORCE_CLIENT_SECRET'),
        hunterApiKey: parseStringEnv('HUNTER_API_KEY'),
        clearbitApiKey: parseStringEnv('CLEARBIT_API_KEY'),
        followUpDelayDays: Math.max(1, parseIntEnv('FOLLOW_UP_DELAY_DAYS', 5)),
        followUpQuestionsDelayDays: Math.max(1, parseIntEnv('FOLLOW_UP_QUESTIONS_DELAY_DAYS', 3)),
        followUpNegativeDelayDays: Math.max(1, parseIntEnv('FOLLOW_UP_NEGATIVE_DELAY_DAYS', 30)),
        followUpNotInterestedDelayDays: Math.max(7, parseIntEnv('FOLLOW_UP_NOT_INTERESTED_DELAY_DAYS', 60)),
        followUpMax: Math.max(1, parseIntEnv('FOLLOW_UP_MAX', 1)),
        followUpDailyCap: Math.max(1, parseIntEnv('FOLLOW_UP_DAILY_CAP', 10)),
    };
}

export function buildProxyDomainConfig(): Partial<AppConfig> {
    return {
        proxyUrl: parseStringEnv('PROXY_URL'),
        proxyUsername: parseStringEnv('PROXY_USERNAME'),
        proxyPassword: parseStringEnv('PROXY_PASSWORD'),
        proxyTypeDefault: parseProxyType(process.env.PROXY_TYPE_DEFAULT, 'residential'),
        proxyListPath: parseStringEnv('PROXY_LIST'),
        proxyFailureCooldownMinutes: Math.max(1, parseIntEnv('PROXY_FAILURE_COOLDOWN_MINUTES', 30)),
        proxyRotateEveryJobs: Math.max(0, parseIntEnv('PROXY_ROTATE_EVERY_JOBS', 0)),
        proxyRotateEveryMinutes: Math.max(0, parseIntEnv('PROXY_ROTATE_EVERY_MINUTES', 0)),
        proxyHealthCheckTimeoutMs: Math.max(1000, parseIntEnv('PROXY_HEALTH_CHECK_TIMEOUT_MS', 5000)),
        proxyMobilePriorityEnabled: parseBoolEnv('PROXY_MOBILE_PRIORITY_ENABLED', true),
        proxyMobileEscalationFailures: Math.max(1, parseIntEnv('PROXY_MOBILE_ESCALATION_FAILURES', 2)),
        proxyProviderApiEndpoint: parseStringEnv('PROXY_PROVIDER_API_ENDPOINT'),
        proxyProviderApiKey: parseStringEnv('PROXY_PROVIDER_API_KEY'),
        fingerprintApiEndpoint: parseStringEnv('FINGERPRINT_API_ENDPOINT'),
        mobileProbability: Math.min(1, Math.max(0, parseFloatEnv('MOBILE_PROBABILITY', 0.3))),
        useJa3Proxy: parseBoolEnv('USE_JA3_PROXY', false),
        ja3ProxyPort: Math.max(1, parseIntEnv('JA3_PROXY_PORT', 8080)),
        ja3Fingerprint: parseStringEnv('JA3_FINGERPRINT', '771,4865-4867-4866-49195-49199-52393-52392-49196-49200-49162-49161-49171-49172-51-57-47-53-10,0-23-65281-10-11-35-16-5-51-43-13-45-28-21,29-23-24-25-256-257,0'),
        ja3UserAgent: parseStringEnv('JA3_USER_AGENT', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:115.0) Gecko/20100101 Firefox/115.0'),
        ja3ProxyUpstream: parseStringEnv('JA3_PROXY_UPSTREAM'),
        ssiDynamicLimitsEnabled: parseBoolEnv('SSI_DYNAMIC_LIMITS_ENABLED', true),
        ssiStateKey: parseStringEnv('SSI_STATE_KEY', 'linkedin_ssi_score'),
        ssiDefaultScore: Math.min(100, Math.max(0, parseIntEnv('SSI_DEFAULT_SCORE', 55))),
        ssiInviteMin: Math.max(1, parseIntEnv('SSI_INVITE_MIN', 30)),
        ssiInviteMax: Math.max(1, parseIntEnv('SSI_INVITE_MAX', 80)),
        ssiMessageMin: Math.max(1, parseIntEnv('SSI_MESSAGE_MIN', 20)),
        ssiMessageMax: Math.max(1, parseIntEnv('SSI_MESSAGE_MAX', 40)),
        warmupEnabled: parseBoolEnv('WARMUP_ENABLED', false),
        warmupStartDate: parseStringEnv('WARMUP_START_DATE') || undefined,
        warmupMaxDays: Math.max(1, parseIntEnv('WARMUP_MAX_DAYS', 30)),
        warmupMinActions: Math.max(1, parseIntEnv('WARMUP_MIN_ACTIONS', 5)),
    };
}

export function buildBehaviorDomainConfig(): Partial<AppConfig> {
    return {
        withdrawInvitesEnabled: parseBoolEnv('WITHDRAW_INVITES_ENABLED', true),
        pendingInviteMaxDays: parseIntEnv('PENDING_INVITE_MAX_DAYS', 30),
        inviteWithNote: parseBoolEnv('INVITE_WITH_NOTE', false),
        inviteNoteMode: (parseStringEnv('INVITE_NOTE_MODE', 'template') === 'ai' ? 'ai' : 'template') as 'template' | 'ai',
        salesNavSyncEnabled: parseBoolEnv('SALESNAV_SYNC_ENABLED', false),
        salesNavSyncListName: parseStringEnv('SALESNAV_SYNC_LIST_NAME', 'default'),
        salesNavSyncListUrl: parseStringEnv('SALESNAV_SYNC_LIST_URL'),
        salesNavSyncMaxPages: Math.max(1, parseIntEnv('SALESNAV_SYNC_MAX_PAGES', 3)),
        salesNavSyncIntervalHours: Math.max(1, parseIntEnv('SALESNAV_SYNC_INTERVAL_HOURS', 24)),
        salesNavSyncLimit: Math.max(1, parseIntEnv('SALESNAV_SYNC_LIMIT', 30)),
        salesNavSyncAccountId: parseStringEnv('SALESNAV_SYNC_ACCOUNT_ID'),
        rampUpEnabled: parseBoolEnv('RAMPUP_ENABLED', true),
        rampUpDailyIncrease: Math.max(0.01, Math.min(0.5, parseFloatEnv('RAMPUP_DAILY_INCREASE', 0.05))),
        rampUpMaxCap: Math.max(1, parseIntEnv('RAMPUP_MAX_CAP', 80)),
        randomActivityEnabled: parseBoolEnv('RANDOM_ACTIVITY_ENABLED', false),
        randomActivityProbability: Math.min(1, Math.max(0, parseFloatEnv('RANDOM_ACTIVITY_PROBABILITY', 0.15))),
        randomActivityMaxActions: Math.max(1, parseIntEnv('RANDOM_ACTIVITY_MAX_ACTIONS', 3)),
        interJobMinDelaySec: Math.max(1, parseIntEnv('INTER_JOB_MIN_DELAY_SEC', 45)),
        interJobMaxDelaySec: Math.max(1, parseIntEnv('INTER_JOB_MAX_DELAY_SEC', 90)),
        behaviorDecoyMinIntervalJobs: Math.max(1, parseIntEnv('DECOY_MIN_INTERVAL_JOBS', 3)),
        behaviorDecoyMaxIntervalJobs: Math.max(1, parseIntEnv('DECOY_MAX_INTERVAL_JOBS', 5)),
        behaviorCoffeeBreakMinIntervalJobs: Math.max(1, parseIntEnv('COFFEE_BREAK_MIN_INTERVAL_JOBS', 10)),
        behaviorCoffeeBreakMaxIntervalJobs: Math.max(1, parseIntEnv('COFFEE_BREAK_MAX_INTERVAL_JOBS', 15)),
        behaviorCoffeeBreakMinSec: Math.max(60, parseIntEnv('COFFEE_BREAK_MIN_SEC', 180)),
        behaviorCoffeeBreakMaxSec: Math.max(60, parseIntEnv('COFFEE_BREAK_MAX_SEC', 420)),
        contextualPauseMinMs: Math.max(200, parseIntEnv('CONTEXTUAL_PAUSE_MIN_MS', 900)),
        contextualPauseMaxMs: Math.max(200, parseIntEnv('CONTEXTUAL_PAUSE_MAX_MS', 4200)),
        mondayLowActivityFactor: Math.min(1, Math.max(0.1, parseFloatEnv('MONDAY_LOW_ACTIVITY_FACTOR', 0.7))),
        mondayLowActivityStartHour: Math.max(0, parseIntEnv('MONDAY_LOW_ACTIVITY_START_HOUR', 9)),
        mondayLowActivityEndHour: Math.max(0, parseIntEnv('MONDAY_LOW_ACTIVITY_END_HOUR', 12)),
        fridayLowActivityFactor: Math.min(1, Math.max(0.1, parseFloatEnv('FRIDAY_LOW_ACTIVITY_FACTOR', 0.75))),
        fridayLowActivityStartHour: Math.max(0, parseIntEnv('FRIDAY_LOW_ACTIVITY_START_HOUR', 15)),
        fridayLowActivityEndHour: Math.max(0, parseIntEnv('FRIDAY_LOW_ACTIVITY_END_HOUR', 18)),
        weekendPolicyEnabled: parseBoolEnv('WEEKEND_POLICY_ENABLED', true),
        timingExplorationProbability: Math.min(0.5, Math.max(0, parseFloatEnv('TIMING_EXPLORATION_PROBABILITY', 0.1))),
        greenModeEnabled: parseBoolEnv('GREEN_MODE_ENABLED', false),
        greenModeStartHour: Math.max(0, parseIntEnv('GREEN_MODE_START_HOUR', 21)),
        greenModeEndHour: Math.max(0, parseIntEnv('GREEN_MODE_END_HOUR', 7)),
        greenModeBudgetFactor: Math.min(1, Math.max(0.1, parseFloatEnv('GREEN_MODE_BUDGET_FACTOR', 0.6))),
        greenModeIntervalMultiplier: Math.max(1, parseFloatEnv('GREEN_MODE_INTERVAL_MULTIPLIER', 1.5)),
    };
}
